apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  mongo-uri: "mongodb+srv://read-write:read-write@sunnyredhu-x5vx1.mongodb.net/jhakhaas?retryWrites=true&w=majority"
  google-client-id: "1039182140359-6ra6trnm1ah0g69ljm5hshn5ntdile7r.apps.googleusercontent.com"
  google-client-secret: "fxjWTnlqyx8lA-EvKeO5zQuO"
  google-redirect-uri: "http://www.abcdpractice.com/auth/google/callback"