node {
  try {
    stage('stageName') {
      checkout scm
      sh 'printenv'
    }
  } catch (err) {
    echo "Error: ${err}"
  } finally {
    // Cleanup workspace after build completion
    cleanWs(notFailBuild: true)
  }
}